apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_USER: YWRtaW5teXNxbA==          # adminmysql
  DB_PASS: ZGJhZG1pbm15c3Fs          # dbadminmysql
  DB_ROOT_PASS: a3ViZXJuZXRlc3Bhc3M= # kubernetespass