apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-custom
  template:
    metadata:
      name: nginx-custom
      labels:
        name: nginx-custom
    spec:
      containers:
        - name: nginx
          image: sigitkurniawan0207/nginx-custom:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-service
spec:
  selector:
    name: nginx-custom
  ports:
    - port: 8080
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    name: curl
spec:
  containers:
    - name: curl
      image: khannedy/nginx-curl
