apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-volume
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-volume
  template:
    metadata:
      name: nginx-volume
      labels:
        name: nginx-volume
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: nodejs-writer
          image: khannedy/nodejs-writer
          volumeMounts:
            - mountPath: /app/html
              name: html
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: nginx-volume
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30002